const tagList=[
    {value:"aap", label:"aap"},
    {value:"address/name issue", label:"address/name issue"}, 
    {value:"all customer", label:"all customer"},
    {value:"atd", label:"atd"}, 
    {value:"audit/watcher", label:"audit/watcher"},
    {value:"back end", label:"back end"},
    {value:"back-end", label:"back-end"}, 
    {value:"blue green", label:"blue green"},
    {value:"blue team", label:"blue team"},
    {value:"bug", label:"bug"},
    {value:"bugs", label:"bugs"},
    {value:"cd", label:"cd"},
    {value:"ci", label:"ci"},
    {value:"contract(s)", label:"contract(s)"},
    {value:"core", label:"core"},
    {value:"cx", label:"cx",},
    {value:"data engineering", label:"data engineering"},
    {value:"design", label:"design"},
    {value:"devs", label:"devs"},
    {value:"dispatching issue", label:"dispatching issue"},
    {value:"door dash", label:"door dash"},
    {value:"duplicate", label:"duplicate"},
    {value:"edi", label:"edi"},
    {value:"engineering", label:"engineering"},
    {value:"epic", label:"epic"},
    {value:"escalation", label:"escalation"},
    {value:"eta", label:"eta"},
    {value:"extra", label:"extra"},
    {value:"feature-enhancement", label:"feature-enhancement"},
    {value:"featureflags", label:"featureflags"},
    {value:"fedex", label:"fedex"}, 
    {value:"filter/sort issue", label:"filter/sort issue"},
    {value:"front end", label:"front end"},
    {value:"front-end", label:"front-end"},
    {value:"global", label:"global"},
    {value:"green", label:"green"},
    {value:"green team", label:"green team"},
    {value:"high-impact", label:"high-impact"},
    {value:"holiday", label:"holiday"},
    {value:"hotfix", label:"hotfix"},
    {value:"implementation", label:"implementation"},
    {value:"insert", label:"insert"},
    {value:"integrations", label:"integrations"}, 
    {value:"limestone", label:"limestone"},
    {value:"logistics", label:"logistics"}, 
    {value:"lp portal", label:"lp portal"},
    {value:"lp pricing", label:"lp pricing"},
    {value:"menard", label:"menard"},
    {value:"menards", label:"menards"},
    {value:"milton cat", label:"milton cat"},
    {value:"miltoncat", label:"miltoncat"}, 
    {value:"mobile", label:"mobile"},
    {value:"not a bug", label:"not a bug"}, 
    {value:"notifications", label:"notifications"}, 
    {value:"ops", label:"ops"},
    {value:"ord", label:"ord"},
    {value:"order status", label:"order status"},
    {value:"pepsi", label:"pepsi"}, 
    {value:"petpeople", label:"petpeople"}, 
    {value:"plugin", label:"plugin"}, 
    {value:"pod issue", label:"pod issue"}, 
    {value:"qa", label:"qa"}, 
    {value:"red", label:"red"}, 
    {value:"red team", label:"red team"}, 
    {value:"rel-team", label:"rel-team"}, 
    {value:"reporting", label:"reporting"}, 
    {value:"returns", label:"returns"}, 
    {value:"revoke", label:"revoke"}, 
    {value:"risk", label:"risk"}, 
    {value:"risk-mit", label:"risk-mit"},
    {value:"routing issue", label:"routing issue"}, 
    {value:"scaling", label:"scaling"},
    {value:"skullcandy", label:"skullcandy"},
    {value:"staging", label:"staging"},
    {value:"support", label:"support"},
    {value:"synthetic events", label:"synthetic events"},
    {value:"tbc", label:"tbc"},
    {value:"tech debt", label:"tech debt"}, 
    {value:"technical design", label:"technical design"},
    {value:"test(s)", label:"test(s)"}
]

export {tagList}